views:
  - title: Home
    header:
      card:
        type: markdown
        text_only: true
        content: |-
          # 智能会议室
          ---
          * 请大家注意了，这只是一个测试功能
    badges:
      - type: entity
        entity: weather.forecast_wo_de_jia
      - type: entity
        show_name: true
        show_state: false
        show_icon: true
        entity: sensor.nas_drive_1_status
        name: 主机
        color: green
        show_entity_picture: true
        icon: mdi:nas
    sections:
      - type: grid
        cards:
          - type: heading
            heading_style: title
            heading: ' 视频矩阵切换'
            tap_action:
              action: none
          - type: entities
            title: 客厅电视 (输出 1)
            entities:
              - type: button
                name: 输入 1 (机顶盒)
                icon: mdi:alarm-light
                tap_action:
                  action: call-service
                  service: script.send_tcp_command_script
                  data:
                    ip_address: 192.168.3.116
                    port_number: 4001
                    command_string: kaixin001
              - type: button
                name: 输入 2 (游戏机)
                icon: mdi:gamepad-variant
                tap_action:
                  action: call-service
                  service: script.send_tcp_command_script
                  data:
                    ip_address: 192.168.3.116
                    port_number: 4001
                    command_string: kaixin002
              - type: button
                name: 输入 3 (蓝光播放器)
                icon: mdi:disc-player
                tap_action:
                  action: call-service
                  service: script.send_tcp_command_script
                  data:
                    ip_address: 192.168.3.116
                    port_number: 4001
                    command_string: kaixin003
              - type: button
                name: 输入 4 (PC)
                icon: mdi:desktop-tower
                tap_action:
                  action: call-service
                  service: script.send_tcp_command_script
                  data:
                    ip_address: 192.168.3.116
                    port_number: 4001
                    command_string: kaixin004
            grid_options:
              columns: 6
              rows: auto
          - type: entities
            entities:
              - entity: input_select.matrix_source_selector
              - entity: input_select.matrix_destination_selector
              - entity: script.execute_matrix_switch
            grid_options:
              columns: 6
              rows: auto
          - show_name: true
            show_icon: true
            type: button
            name: 客厅空调 - 开
            icon: file:jz
            show_state: false
            tap_action:
              action: perform-action
              data:
                ip_address: 192.168.3.28
                port_number: 1222
                command_string: A5 C3 3C 5A FF 36 02 01 01 EE
                append_carriage_return: false
                send_as_hex: true
                encoding: ascii
              perform_action: script.send_tcp_command_script
              target: {}
            hold_action:
              action: more-info
          - show_name: true
            show_icon: true
            type: button
            name: 客厅空调 - 关
            icon: mdi:air-conditioner
            show_state: false
            tap_action:
              action: perform-action
              data:
                ip_address: 192.168.3.116
                port_number: 4001
                command_string: yuanzhou
                append_carriage_return: false
                send_as_hex: false
                encoding: utf-8
              perform_action: script.send_tcp_command_script
              target: {}
            hold_action:
              action: more-info
          - show_name: true
            show_icon: false
            type: button
            icon: ''
            tap_action:
              action: perform-action
              perform_action: script.send_rs232_data_script
              data:
                port: /dev/ttyS1
                baudrate: 9600
                bytesize: '8'
                parity: 'N'
                stopbits: '1.0'
                timeout: 1
                is_hex: true
                read_response: false
                encoding: ascii
                data: A5 C3 3C 5A FF 36 03 03 02 00 01 EE
              target: {}
            grid_options:
              columns: 3
              rows: 1
            show_state: false
            name: 静音
